"""The OS boundary implemented by X11Backend and simulated in adapter tests."""

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from PIL.Image import Image


class DesktopBackend(Protocol):
    def size(self) -> tuple[int, int]: ...
    def active_window(self) -> int: ...
    def application_matches(self, session: dict) -> bool: ...
    def screenshot(self) -> Image: ...
    def click(self, x: int, y: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def type_character(self, character: str) -> None: ...
    def key_down(self, key: str) -> None: ...
    def key_up(self, key: str) -> None: ...
    def scroll(self, amount: int) -> None: ...
    def close(self) -> None: ...
